services:
  - type: web
    name: parlasubito-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: GEMINI_API_KEY
        sync: false